// ITEM CODES ARE IN NUMBER ORDER EVERYWHERE, AND IT IS NOT A SETTING (17.95).
//  "I think we need a better way to organize the items when creating placements in
//   floorplan view. How do we make sure items get recoded in a numerical order in all
//   areas of the presentation including elevations, frame dashboard, and deck studio"
//  "I do not want it to be a choice, it has to be set in stone, I do not want designer
//   presentations looking different from one another."
// The reported project: the dashboard read ART.1, ART.3, ART.2, EGD.1, WF.1, ART.4,
// EGD.2; the floorplan Items list 01, 03, 02, 04; the wall rail Elevation 1, ART.1,
// ART.2, ART.4.
const fs = require('fs');
const path = require('path');
const { JSDOM } = require('jsdom');
const root = path.join(__dirname, '..');
const APP = fs.readFileSync(path.join(root, 'app.js'), 'utf8');
const HTML = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const NL = String.fromCharCode(10);

const dom = new JSDOM(HTML, { url: 'https://example.com/', pretendToBeVisual: true, runScripts: 'outside-only' });
const { window } = dom;
window.HTMLCanvasElement.prototype.getContext = () => ({});
window.fetch = () => Promise.reject(new Error('no network in test'));
global.window = window; global.document = window.document; global.navigator = window.navigator;

const body = [
  '_autosaveToldUser = true;',
  '_dsRefresh = function () {}; _dsRenderCenter = function () {}; _dsRenderRail = function () {}; _dsRenderTools = function () {};',
  'var __toasts = []; _toast = function (a, b) { __toasts.push(a + " | " + (b || "")); return null; };',
  'window.__res = (async function () {',
  '  const out = [];',
  '  const check = async function (label, fn) { try { await fn(); out.push({ label: label, ok: true }); } catch (e) { out.push({ label: label, ok: false, err: e.message }); } };',
  '  const mk = function (id, product, cat) { return Object.assign(JSON.parse(JSON.stringify(dashDefaultData)), { id: id, product: product || "Framed Art", category: cat || "framed", notes: "was " + id }); };',
  '  const fr = function (id, x) { return { id: id, letter: "A", x: x || 10, y: 40, w: 24, h: 24, active: true }; };',
  // The project in the screenshots, rows in the order they were stored.
  '  const reported = function () {',
  '    editorialContent = _editorialDefaults();',
  '    dashProjectData = [mk("ART.1A"), mk("ART.1B"), mk("ART.3"), mk("ART.2A"), mk("ART.2B"), mk("ART.2C"),',
  '      mk("EGD.1", "Wallcovering (EGD)", "egd"), mk("WF.1", "Window Film (WF)", "wf")]',
  '      .concat("ABCDEFG".split("").map(function (L) { return mk("ART.4" + L); }))',
  '      .concat([mk("EGD.2", "Wallcovering (EGD)", "egd")]);',
  '    elevations = [',
  '      { id: "w0", name: "Elevation 1", wallW: 185, wallH: 108, personPos: { x: -60 }, frames: [] },',
  '      { id: "w1", name: "ART.1 LOBBY", wallW: 144, wallH: 108, personPos: { x: -60 }, frames: [fr("ART.1A"), fr("ART.1B", 40)] },',
  '      { id: "w2", name: "ART.2 LOBBY", wallW: 144, wallH: 108, personPos: { x: -60 }, frames: [fr("ART.2A"), fr("ART.2B", 40), fr("ART.2C", 70)] },',
  '      { id: "w4", name: "ART.4 LOBBY", wallW: 144, wallH: 108, personPos: { x: -60 }, frames: "ABCDEFG".split("").map(function (L, i) { return fr("ART.4" + L, i * 20); }) },',
  '    ];',
  '    currentElevIndex = 3; elevFrames = elevations[3].frames;',
  '    dashSelectedRowIndex = 0; dashMultiSelectedIndices.clear();',
  '    undoStack.length = 0; redoStack.length = 0; _isFirstHistoryPush = true;',
  '    __toasts.length = 0;',
  '  };',
  '  const ids = function () { return dashProjectData.map(function (r) { return r.id; }).join(); };',
  '  const keys = function () { return _fpGroups().map(function (g) { return g.key; }).join(); };',
  '  const walls = function () { return elevations.map(function (e) { return e.name; }).join(); };',
  '  const was = function (id) { return ((dashProjectData.find(function (r) { return r.id === id; }) || {}).notes || "").slice(4); };',
  '  const SORTED = "ART.1A,ART.1B,ART.2A,ART.2B,ART.2C,ART.3,ART.4A,ART.4B,ART.4C,ART.4D,ART.4E,ART.4F,ART.4G,EGD.1,EGD.2,WF.1";',
  '',
  '  await check("EXACT BUG: the reported project settles into number order in the dashboard, the Items list and the wall rail", async function () {',
  '    reported();',
  '    _codesSettle();',
  '    if (ids() !== SORTED) throw new Error("dashboard " + ids());',
  '    if (keys() !== "ART.1,ART.2,ART.3,ART.4,EGD.1,EGD.2,WF.1") throw new Error("Items list " + keys());',
  '    if (_fpGroups().slice(0, 4).map(function (g) { return g.num; }).join() !== "01,02,03,04") throw new Error("plan numbers");',
  '    if (walls() !== "ART.1 LOBBY,ART.2 LOBBY,ART.4 LOBBY,Elevation 1") throw new Error("walls " + walls());',
  '    if (elevations[currentElevIndex].name !== "ART.4 LOBBY") throw new Error("the open wall changed under the designer");',
  '  });',
  '',
  '  await check("Deck Studio spec pages come out in the same order", async function () {',
  '    reported();',
  '    _deckPageList();',
  '    const spec = _deckSpecRows().map(function (r) { return r.id; }).join();',
  '    if (spec !== SORTED) throw new Error(spec);',
  '  });',
  '',
  '  await check("opening a project puts it in order and closes its gaps", async function () {',
  '    reported();',
  '    // A gap only the load can close: ART.4 saved as ART.6 (sorting alone would leave it).',
  '    dashProjectData.forEach(function (r) { r.id = r.id.split("ART.4").join("ART.6"); });',
  '    elevations.forEach(function (e) { e.frames.forEach(function (f) { f.id = f.id.split("ART.4").join("ART.6"); }); });',
  '    const text = JSON.stringify({ type: "master-studio-project", dashUnit: "in", elevUnit: "in", dashProjectData: dashProjectData, elevations: elevations, editorial: editorialContent });',
  '    dashProjectData = [mk("ART.1")]; elevations = [{ id: "z", name: "z", wallW: 100, wallH: 100, frames: [] }];',
  '    _readProjectText(text);',
  '    if (ids() !== SORTED) throw new Error(ids());',
  '  });',
  '',
  '  await check("deleting a code closes the gap, and the wall and its name follow", async function () {',
  '    reported(); _codesSettle();',
  '    dashSelectedRowIndex = dashProjectData.findIndex(function (r) { return r.id === "ART.3"; });',
  '    deleteDashRow();',
  '    if (ids().indexOf("ART.4") >= 0) throw new Error("ART.4 did not move up: " + ids());',
  '    if (was("ART.3A") !== "ART.4A") throw new Error("ART.3A is " + was("ART.3A"));',
  '    const w = elevations.find(function (e) { return e.id === "w4"; });',
  '    if (w.name !== "ART.3 LOBBY") throw new Error("wall name " + w.name);',
  '    if (w.frames.map(function (f) { return f.id; }).join() !== "ART.3A,ART.3B,ART.3C,ART.3D,ART.3E,ART.3F,ART.3G") throw new Error("frames " + w.frames.map(function (f) { return f.id; }));',
  '  });',
  '',
  '  await check("EXACT ASK: dragging ART.4 above ART.1 in the Items list makes it ART.1 and moves the rest down", async function () {',
  '    reported(); _codesSettle();',
  '    _fpMoveCode("ART.4", "ART.1", false);',
  '    if (was("ART.1A") !== "ART.4A" || was("ART.1G") !== "ART.4G") throw new Error("ART.1A is " + was("ART.1A"));',
  '    if (was("ART.2A") !== "ART.1A" || was("ART.3A") !== "ART.2A" || was("ART.4") !== "ART.3") throw new Error(ids());',
  '    if (ids().indexOf("ART.1A,ART.1B,ART.1C,ART.1D,ART.1E,ART.1F,ART.1G,ART.2A,ART.2B,ART.3A") !== 0) throw new Error("rows " + ids());',
  '    if (walls().indexOf("ART.1 LOBBY,ART.2 LOBBY,ART.3 LOBBY") !== 0) throw new Error("walls " + walls());',
  '    if (elevations[0].id !== "w4") throw new Error("the moved wall is not first");',
  '  });',
  '',
  '  await check("one Ctrl+Z undoes a drag renumber", async function () {',
  '    reported(); _codesSettle(); pushHistory();',
  '    const before = ids();',
  '    _fpMoveCode("ART.3", "ART.1", false);',
  '    if (ids() === before) throw new Error("nothing moved");',
  '    undo();',
  '    if (ids() !== before) throw new Error("undo left " + ids());',
  '  });',
  '',
  '  await check("a drag cannot cross types (that is the category chip)", async function () {',
  '    reported(); _codesSettle();',
  '    const before = ids();',
  '    if (_fpMoveCode("EGD.1", "ART.1", false) !== null) throw new Error("it moved");',
  '    if (ids() !== before) throw new Error(ids());',
  '  });',
  '',
  '  await check("typing a number in the dashboard MOVES the placement there", async function () {',
  '    reported(); _codesSettle();',
  '    const i = dashProjectData.findIndex(function (r) { return r.id === "ART.3"; });',
  '    const inp = document.createElement("input"); inp.value = "ART.1";',
  '    _codesCommitRowId(i, inp);',
  '    if (was("ART.1") !== "ART.3") throw new Error("ART.1 is " + was("ART.1") + " / " + ids());',
  '    if (was("ART.2A") !== "ART.1A" || was("ART.3A") !== "ART.2A") throw new Error(ids());',
  '    if (ids().indexOf("ART.1,ART.2A") !== 0) throw new Error("not sorted " + ids());',
  '  });',
  '',
  '  await check("a number past the end goes to the end, never leaving a gap", async function () {',
  '    reported(); _codesSettle();',
  '    const i = dashProjectData.findIndex(function (r) { return r.id === "ART.1A"; });',
  '    const inp = document.createElement("input"); inp.value = "ART.9A";',
  '    _codesCommitRowId(i, inp);',
  '    if (was("ART.4A") !== "ART.1A" || was("ART.4B") !== "ART.1B") throw new Error(ids());',
  '    if (ids().indexOf("ART.9") >= 0) throw new Error("left a gap: " + ids());',
  '  });',
  '',
  '  await check("typing on one piece of a set moves the whole set", async function () {',
  '    reported(); _codesSettle();',
  '    const i = dashProjectData.findIndex(function (r) { return r.id === "ART.4C"; });',
  '    const inp = document.createElement("input"); inp.value = "ART.1C";',
  '    _codesCommitRowId(i, inp);',
  '    if (was("ART.1A") !== "ART.4A" || was("ART.1G") !== "ART.4G") throw new Error(ids());',
  '  });',
  '',
  '  await check("a new prefix recodes it to that type and slots it in by number", async function () {',
  '    reported(); _codesSettle();',
  '    const i = dashProjectData.findIndex(function (r) { return r.id === "ART.3"; });',
  '    const inp = document.createElement("input"); inp.value = "EGD.1";',
  '    _codesCommitRowId(i, inp);',
  '    const r = dashProjectData.find(function (x) { return x.id === "EGD.1"; });',
  '    if (was("EGD.1") !== "ART.3" || r.product !== "Wallcovering (EGD)") throw new Error(ids());',
  '    if (was("EGD.2") !== "EGD.1" || was("EGD.3") !== "EGD.2") throw new Error(ids());',
  '    if (was("ART.3A") !== "ART.4A") throw new Error("ART did not close up " + ids());',
  '  });',
  '',
  '  await check("a code that is not a type and a number is refused and put back", async function () {',
  '    reported(); _codesSettle();',
  '    const before = ids();',
  '    const i = dashProjectData.findIndex(function (r) { return r.id === "ART.3"; });',
  '    const inp = document.createElement("input"); inp.value = "LOBBY";',
  '    _codesCommitRowId(i, inp);',
  '    if (ids() !== before) throw new Error(ids());',
  '    if (inp.value !== "ART.3") throw new Error("the field kept " + inp.value);',
  '  });',
  '',
  '  await check("the elevation frame field follows the same rule (ART.1 moves it, it does not collide)", async function () {',
  '    reported(); _codesSettle();',
  '    const inp = document.createElement("input"); inp.value = "ART.1A"; inp.dataset.originalId = "ART.4A";',
  '    renameFrameId(inp, 0);',
  '    if (was("ART.1A") !== "ART.4A") throw new Error(ids());',
  '  });',
  '',
  '  await check("EXACT BUG (side): typing in the code field no longer renames wall frames per keystroke", async function () {',
  '    reported(); _codesSettle();',
  '    dashSelectedRowIndex = dashProjectData.findIndex(function (r) { return r.id === "ART.2A"; });',
  '    loadDashDataIntoControls(dashProjectData[dashSelectedRowIndex]);',
  '    document.getElementById("m_itemCode").value = "ART.1";',
  '    syncDashAndCalculate();',
  '    const w = elevations.find(function (e) { return e.id === "w2"; });',
  '    if (w.frames[0].id !== "ART.2A") throw new Error("frame renamed mid-typing to " + w.frames[0].id);',
  '    if (dashProjectData[dashSelectedRowIndex].id !== "ART.2A") throw new Error("row renamed mid-typing");',
  '  });',
  '',
  '  await check("dragging a dashboard row to the top renumbers it to 1", async function () {',
  '    reported(); _codesSettle();',
  '    const from = dashProjectData.findIndex(function (r) { return r.id === "ART.3"; });',
  '    reorderDashRow(from, 0);',
  '    if (was("ART.1") !== "ART.3") throw new Error(ids());',
  '    if (ids().indexOf("ART.1,ART.2A") !== 0) throw new Error(ids());',
  '  });',
  '',
  '  await check("a piece dragged out of its placement snaps back and says why", async function () {',
  '    reported(); _codesSettle();',
  '    const before = ids();',
  '    const from = dashProjectData.findIndex(function (r) { return r.id === "ART.2B"; });',
  '    reorderDashRow(from, dashProjectData.length - 1);',
  '    if (ids() !== before) throw new Error(ids());',
  '    if (!__toasts.some(function (t) { return t.indexOf("number order") >= 0; })) throw new Error("silent snap-back");',
  '  });',
  '',
  '  await check("the wall rail drag cannot put walls out of code order", async function () {',
  '    reported(); _codesSettle();',
  '    const before = walls();',
  '    reorderElevation(2, 0);',
  '    if (walls() !== before) throw new Error(walls());',
  '  });',
  '',
  '  await check("a structured code keeps its number and a plain one is never renumbered onto it", async function () {',
  '    reported();',
  '    dashProjectData = [mk("ART.2.1A"), mk("ART.1"), mk("ART.5"), mk("ART.7")];',
  '    _codesSettle({ walls: false });',
  '    if (ids() !== "ART.1,ART.2.1A,ART.3,ART.4") throw new Error(ids());',
  '  });',
  '',
  '  await check("new codes from + Add code sort in behind their own type", async function () {',
  '    reported(); _codesSettle();',
  '    _fpAddCodes("egd", 1);',
  '    if (ids().indexOf("EGD.1,EGD.2,EGD.3,WF.1") < 0) throw new Error(ids());',
  '  });',
  '',
  '  await check("a renumber redraws once, not once per renamed piece", async function () {',
  '    reported(); _codesSettle();',
  '    let n = 0; const real = drawElevAll; drawElevAll = function () { n++; };',
  '    try { _fpMoveCode("ART.4", "ART.1", false); } finally { drawElevAll = real; }',
  '    if (n > 2) throw new Error(n + " redraws");',
  '  });',
  '',
  '  await check("source: the table cell and the form commit the code, they do not rename per keystroke", async function () {',
  '    if (APP_SRC.indexOf("dashHtIn(${index}, \'id\'") >= 0) throw new Error("table cell still renames per keystroke");',
  '    if (HTML_SRC.indexOf(\'id="m_itemCode" oninput\') >= 0) throw new Error("form field still renames per keystroke");',
  '    if (HTML_SRC.indexOf("_codesCommitFormId(this)") < 0) throw new Error("form field does not commit");',
  '  });',
  '  await check("EXACT ASK: Codes in the dashboard opens the floorplan Items list, and Back returns to the same piece after it was renumbered", async function () {',
  '    reported(); _codesSettle();',
  '    switchView("dashboard");',
  '    const piece = dashProjectData.find(function (r) { return r.id === "ART.4C"; });',
  '    selectDashRow(dashProjectData.indexOf(piece));',
  '    if (!_jumpToCodes()) throw new Error("the jump failed");',
  '    if (currentView !== "deck") throw new Error("view " + currentView);',
  '    const d = _dsPages[_dsIndex];',
  '    if (!d || d.kind !== "floorplan" || _fpPanelTab !== "items") throw new Error("not on the Items list");',
  '    if (!_viewReturn || _viewReturn.at !== "deck" || _viewReturn.view !== "dashboard") throw new Error("no trip back");',
  '    const bar = document.createElement("div"); _returnBarInto(bar, "deck");',
  '    if (!bar.querySelector("button")) throw new Error("no Back button in the Items panel");',
  '    _fpMoveCode("ART.4", "ART.1", false);',
  '    _takeReturnTrip();',
  '    if (currentView !== "dashboard") throw new Error("back went to " + currentView);',
  '    if (dashProjectData[dashSelectedRowIndex] !== piece || piece.id !== "ART.1C") throw new Error("back selected " + (dashProjectData[dashSelectedRowIndex] || {}).id);',
  '  });',
  '',
  '  await check("a deck with no floorplan page says so instead of doing nothing", async function () {',
  '    reported(); _codesSettle();',
  '    switchView("dashboard");',
  '    const real = _deckPageList; _deckPageList = function () { return [{ kind: "fixed", fixed: "cover" }]; };',
  '    let r; try { r = _jumpToCodes(); } finally { _deckPageList = real; }',
  '    if (r !== false) throw new Error("claimed success");',
  '    if (!__toasts.some(function (t) { return t.indexOf("no floorplan page") >= 0; })) throw new Error("silent");',
  '  });',
  '',
  '  await check("the # button in Elevations opens the codes, not a second numbering scheme", async function () {',
  '    if (HTML_SRC.indexOf(\'onclick="openRenumberModal()"\') >= 0) throw new Error("the template renumber is still on the button");',
  '    if (HTML_SRC.split("_jumpToCodes()").length - 1 < 2) throw new Error("Codes is not reachable from both the dashboard and Elevations");',
  '  });',
  '  return out;',
  '})();',
].join(NL);
const quiet = console.error; console.error = () => {};
window.APP_SRC = APP; window.HTML_SRC = HTML;
window.eval(APP + NL + 'var APP_SRC = window.APP_SRC; var HTML_SRC = window.HTML_SRC;' + NL + body);
console.error = quiet;
window.__res.then((results) => {
  const failed = results.filter(r => !r.ok);
  results.forEach(r => { if (!r.ok) console.log('FAIL: ' + r.label + ' — ' + r.err); });
  console.log(NL + '--- Summary ---');
  if (failed.length) console.log(failed.length + ' FAILURES');
  else console.log('ALL PASSED (' + results.length + ')');
});
